--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LegendOfMCPE/xEcon
projects:
  xEcon:
    path: main/
    libs:
      - src: poggit/libasynql/libasynql
        version: ^1.3
      - src: Falkirks/spoondetector/libasynql
        version: ^0
...
