language: php
php:
  - 5.6
branches:
  - master
before_install:
  - pecl install channel://pecl.php.net/pthreads-2.0.8
  - pecl install channel://pecl.php.net/weakref-0.2.4
  - echo | pecl install channel://pecl.php.net/yaml-1.1.1
before_script:
  - cd ..
  - git clone --recursive https://github.com/PocketMine/PocketMine-MP.git ServerDir
  - git clone https://github.com/LegendOfMCPE/StatsCore.git AutoKiller_container
  - git clone https://gist.github.com/6ac745b5ff0283c8c02f.git utils_dir
  - mkdir ServerDir/plugins
  - cp utils_dir/xEcon_tester.php runner.php
  - php runner.php --xecon $TRAVIS_BUILD_DIR
