name: xEcon
author: LegendOfMCPE
version: 1
api: [1.0.0]
load: STARTUP
main: xecon\Main
commands:
  xecon:
    description: xEcon main command
    aliases: [x, xe, econ, xec]
    usage: "/xecon <subcommand|help> (Use '/xecon help' to see the subcommands)"
permissions:
  xecon:
    description: xEcon main permission node, allows full control on xEcon
