---
# Please refer to our documentation https://github.com/LegendOfMCPE/xEcon/blob/master/Documentation.md for help configuring this plugin.
taxes:
  - name: Rich people's tax
    type: BaseTax
    frequency: [1, hr]
    source account: bank
    exempt ops: true
    amount: 500
    min balance: 50000
  - name: Standard tax
    type: AssetsTax
    frequency: [30, min]
    source account: [bank, cash]
    exempt ops: false
    percentage: 5
  - name: Salary tax
    type: \xecon\jobs\SalaryTax
    frequency: [24, hr]
    source account: bank
    exempt ops: false
    percentage: 5
    allowance: 3000
...
