---
database:
  type: sqlite
  mysql:
    host: 127.0.0.1
    username: root
    password: ""
    schema: xecon
    port: 3306
defaultPlayerAccounts:
  # only A-Z, a-z, 0-9, hyphen and underscore are allowed in account names, with no more than 40 characters
  cash:
    balance: 100
    max: 1000
  bank:
    balance: 100
    max: 1000
exchangeRates:
  - from: player:cash
    to: player:bank
    interest: 0.12
  - from: player:cash
    to: player:bank
    amount: ">=500"
    interest: 0.11
  - from: player:cash
    to: player:bank
    interest: 0.1
  - from: bank
    to: cash
    amount: ">=1000"
    interest: 0.1
...

