---
database:
  type: sqlite
  mysql:
    host: 127.0.0.1
    username: root
    password: ""
    schema: xecon
    port: 3306

player:
  modifiers:
    cash:
      max: 3000 # You can't store too much money in your wallet!
    bank:
      min: -1000 # 1000 dollars overdraft!
      # each account should not have more than one modifier that declares interest. Otherwise, undefined behaviour may occur.
      interest:
        - compound: 1.001 # new/old ratio
          every: 1 day # frequency of compounding the interest
          if: ">= 1000" # if the balance matches the range
          priority: 10 # the interest rule with the HIGHEST priority number will be chosen if multiple rules match the range
                      # if multiple interest rules with the same priority number match the range, the first one will be chosen.
                      # default priority = 5
        - compound: 1.1 # this collects 10% overdraft fee, since the balance is negative
          every: 7 day
          if: "< 0"
          priority: 15
      # If the balance compounds and the balance falls below the minimum amount **specified by this modifier**, do the
      # specified actions one by one. Options:
      ## null: Do nothing, skip to the next step directly (if any).
      ## auto-deposit: For every other account owned by the player, if an exchange rate path exists from it to
      ##               this bank account and its balance is positive, try to deposit money from it into this bank
      ##               account until its balance becomes zero. If the bank account balance is still negative, go to the
      ##               next step.
      ## declare-bankrupt: Tell other plugins that this player is bankrupt. Other plugins may try to automatically sell
      ##                   things owned by this player. If the bank balance is still negative, go to the next step.
      ## zero-all: Set all account balances to zero, then go to the next step.
      ## ban: Ban the player's username, then go to the next step.
      uponBankrupt:
        - auto-deposit
        - declare-bankrupt
        - zero-all
    dollar:
      unit: "$%g"
    coin:
      unit: "%g coins"

  defaultAccounts:
    cash:
      balance: 100
      modifiers: [cash, dollar]
    bank:
      balance: 100
      modifiers: [bank, dollar]
    coins:
      balance: 5
      modifiers: [coin]

exchangeRates:
  - from: player:cash
    to: player:bank
    rate: 0.98
  - from: player:coin
    to: player:dollar
    rate: 1337
...
