---
economies:
  '#README': Each economy is run independently from one another. You can assume there is only one economy called main if you don't need to use this new feature.
  - name: main
    data-provider:
      '#README': xEcon is shipped with two default data providers, namely sqlite3 and mysql. The default options for sqlite3 and mysql are shown as below. Note that each economy has its own data provider.
      name: sqlite3
      options:
        path: main.sq3
#      name: mysql
#      options:
#        connection-details:
#          host: 127.0.0.1
#          username: root
#          password: ""
#          schema-name: "xecon"
#        table-prefix: "main_"
default-economy: main

players:
  default-accounts:
    main: # economy name
      cash:
        value: 50
        max-value: 1000
        min-value: 0
      bank:
        value: 1000
        max-value: 1000000
        min-value: -1000

privacy:
  auto-report:
    '#README': You can help us improve xEcon by allowing xEcon to automatically send error reports to the server.
    enabled: true
    host: http://pmt.mcpe.me/LegendsOfMCPE/reportError.php
    scopes: [commands, events, tasks]
...
